application: udacitychirag
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /play.*
  script: play.app
- url: /blog.*
  script: blog.app
- url: /asciichan
  script: asciichan.app
- url: /slist
  script: slist.app
- url: /fizzbuzz
  script: slist.app
- url: /rot
  script: rot.app
- url: /signup
  script: signup.app
- url: /welcome.*
  script: signup.app
- url: /.*
  script: helloworld.app

libraries:
- name: jinja2
  version: latest
